name: Build APK

on:
  push:
    branches:
      - main  # Trigger workflow when pushing to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The environment where the workflow will run

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Gradle Cache
        uses: gradle/gradle-build-action@v2
        with:
          cache: true

      - name: Build APK with Gradle
        run: ./gradlew assembleRelease  # Build the release APK

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk-artifact
          path: app/build/outputs/apk/release/*.apk
