name: Build APK

on:
  push:
    branches:
      - main  # Trigger workflow when pushing to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow for pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # The environment where the workflow will run
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2  # Check out the repository code so the next steps can access it

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'  # You can specify a different JDK version depending on your Android project setup

      - name: Set up Gradle cache
        uses: gradle/gradle-build-action@v2
        with:
          cache: true  # This caches Gradle dependencies to speed up builds

      - name: Start build timing
        run: echo "Start time: $(date)"

      - name: Build APK with Gradle
        run: |
          start_time=$(date +%s)  # Capture start time in seconds
          ./gradlew assembleRelease  # For building the release version, or use assembleDebug for debug version
          end_time=$(date +%s)  # Capture end time in seconds
          elapsed_time=$((end_time - start_time))  # Calculate elapsed time in seconds
          echo "Build took $elapsed_time seconds"

      - name: End build timing
        run: echo "End time: $(date)"

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk-artifact  # Name of the uploaded artifact
          path: app/build/outputs/apk/release/*.apk  # Path to the APK file
